apiVersion: v1
kind: Pod
metadata:
  name: ${service_name}
spec:
  containers:
    - name: ${service_name}
      image: eu.gcr.io/${project}/${image_name}
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 8080
  restartPolicy: Always